=== kert25/6sem_internet_proga/ЛР6/Videoteka.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Schema каталога видеотеки. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="ageRatingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="G"/>
            <xs:enumeration value="PG"/>
            <xs:enumeration value="PG13"/>
            <xs:enumeration value="R"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="mediaFormatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BluRay"/>
            <xs:enumeration value="DVD"/>
            <xs:enumeration value="Digital"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="videotheque">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="directors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="director" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="films">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="film" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="originalTitle" type="xs:string" minOccurs="0"/>
                                        <xs:element name="genre" type="xs:string"/>
                                        <xs:element name="releaseYear" type="xs:gYear"/>
                                        <xs:element name="duration">
                                            <xs:complexType>
                                                <xs:attribute name="minutes" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:positiveInteger">
                                                            <xs:maxInclusive value="600"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="country" type="xs:string"/>
                                        <xs:element name="cast">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="actor" maxOccurs="unbounded">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="role" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="copies">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="copy" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="inventoryNumber" type="xs:ID" use="required"/>
                                                            <xs:attribute name="format" type="mediaFormatType" use="required"/>
                                                            <xs:attribute name="available" type="xs:boolean" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="ageRating" type="ageRatingType" use="required"/>
                                    <xs:attribute name="director" type="xs:IDREF" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="updated" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kert25/6sem_internet_proga/ЛР6/Videoteka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Каталог видеотеки: фильмы, режиссёры и экземпляры носителей. -->
<videotheque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="Videoteka.xsd"
             name="Видеотека ИПМКН" updated="2026-10-01">
    <directors>
        <director id="dirNolan" name="Кристофер Нолан" />
        <director id="dirWachowski" name="Лана и Лилли Вачовски" />
        <director id="dirAllersMinkoff" name="Роджер Аллерс и Роб Минкофф" />
    </directors>
    <films>
        <film id="filmInterstellar" ageRating="PG13" director="dirNolan">
            <title>Интерстеллар</title>
            <originalTitle>Interstellar</originalTitle>
            <genre>Научная фантастика</genre>
            <releaseYear>2014</releaseYear>
            <duration minutes="169" />
            <country>США, Великобритания</country>
            <cast>
                <actor role="Купер">Мэттью Макконахи</actor>
                <actor role="Амелия Брэнд">Энн Хэтэуэй</actor>
            </cast>
            <description>Экспедиция отправляется через червоточину, чтобы найти новый дом для человечества.</description>
            <copies>
                <copy inventoryNumber="copyInterstellarBluRay" format="BluRay" available="true" />
                <copy inventoryNumber="copyInterstellarDvd" format="DVD" available="false" />
            </copies>
        </film>
        <film id="filmMatrix" ageRating="R" director="dirWachowski">
            <title>Матрица</title>
            <originalTitle>The Matrix</originalTitle>
            <genre>Фантастика</genre>
            <releaseYear>1999</releaseYear>
            <duration minutes="136" />
            <country>США</country>
            <cast>
                <actor role="Нео">Киану Ривз</actor>
                <actor role="Тринити">Кэрри-Энн Мосс</actor>
            </cast>
            <description>Программист узнаёт, что привычный мир является компьютерной симуляцией.</description>
            <copies>
                <copy inventoryNumber="copyMatrixBluRay" format="BluRay" available="true" />
            </copies>
        </film>
        <film id="filmLionKing" ageRating="G" director="dirAllersMinkoff">
            <title>Король Лев</title>
            <originalTitle>The Lion King</originalTitle>
            <genre>Анимация</genre>
            <releaseYear>1994</releaseYear>
            <duration minutes="88" />
            <country>США</country>
            <cast>
                <actor role="Симба">Мэттью Бродерик</actor>
                <actor role="Муфаса">Джеймс Эрл Джонс</actor>
            </cast>
            <description>История взросления львёнка Симбы и его возвращения в Земли Прайда.</description>
            <copies>
                <copy inventoryNumber="copyLionKingDvd" format="DVD" available="true" />
            </copies>
        </film>
    </films>
</videotheque>
